# Generated by Django 4.0.4 on 2022-04-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_by', models.CharField(max_length=40)),
                ('feedback_email', models.EmailField(max_length=254)),
                ('feedback', models.CharField(max_length=250)),
            ],
        ),
    ]
