# Generated by Django 4.0.4 on 2022-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_contact_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Orthopedic', 'Orthopedic'), ('Gynecologist', 'Gynecologist'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Neurologists', 'Neurologists'), ('Urology', 'Urology'), ('Pathology', 'Pathology'), ('Dentist', 'Dentist')], default='Cardiologist', max_length=50),
        ),
    ]
